version: "3.8"

services:
  docker:
    # image: kuznetcovay/dind:v1.0.3
    image: docker:dind
    container_name: docker
    command: dockerd --tls=false --insecure-registry=myregistry.example.com:5000 -H tcp://0.0.0.0:2375
    volumes:
      - ${HOME}/.docker/config.json:/app/dockerconfig/config.json:ro
      - dind-storage:/var/lib/docker
      - dind-docker-certs-ca:/certs/ca
      - dind-docker-certs-client:/certs/client
    ports:  # Expose port 2375,2376
      - "2375:2375"      
      # - "2376:2376"      
    privileged: true
    environment:                    
      - DOCKER_TLS_CERTDIR=/certs                
    networks:
      - dind-network
    security_opt:
      - label:disable

  cdddru:
    image: kuznetcovay/cdddru:${DOCKER_IMAGE_TAG:-dev-v1.0.3}
    # image: docker:latest
    container_name: cdddru
    hostname: cdddru-container
    depends_on:
      - docker
    command: >
      /bin/sh -c "
                  #/app/cdddru -f /app/jobs/config.json -v
                  tail -f /dev/null"
    environment:  
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_TLS_CERTDIR=""
    working_dir: /source
    volumes:
      - ${HOME}/.docker/config.json:/.bind/configs/dockerconfig/config.json:ro
      - ${HOME}/.ssh/id_rsa:/.bind/configs/gitcred/id_rsa:ro
      - ${HOME}/.kube/config_ddru:/.bind/configs/kubeconfig/config:ro
      - dind-docker-certs-client:/certs/client:ro
      - ./:/source
    networks:
      - dind-network      

networks:
  dind-network:
    external: true    

volumes:
  dind-storage:
    external: true
  dind-docker-certs-ca:
    external: true
  dind-docker-certs-client:
    external: true