apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdddru-nfs-02
  namespace: test-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-ddru-02
  namespace: test-app
  labels:
    app: cd-ddru-02
    release: v1.0.1
spec:
  selector:
    matchLabels:
      app: cd-ddru-02
  template:
    metadata:
      labels:
        app: cd-ddru-02
    spec:
      containers:
        # docker_in_docker container
        - name: dind
          image: docker:dind
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: dockerconfig
              mountPath: /root/.docker
              readOnly: true
            - name: dind-storage
              mountPath: /var/lib/docker
          ports:
            - containerPort: 2375
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true

        # container with cdddru binary
        - name: cdddru
          image: kuznetcovay/cdddru:v1.0.15
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          command: [
              "/bin/sh",
              "-c",
              "/app/cdddru /app/jobs/config-main-ddru.yaml -v;",
            ]

          imagePullPolicy: Always

          volumeMounts:
            - name: dockerconfig
              mountPath: /.bind/configs/dockerconfig

            - name: gitcred
              mountPath: /.bind/configs/gitcred

            - name: kubeconfig
              mountPath: /.bind/configs/kubeconfig

              # volume from home nas server to sync main-site data
            - name: site-data
              mountPath: /app/ext-data
              subPath: main

              # volume from nfs server (on master node) to store jobs files
            - name: nfs-store-02
              mountPath: /app/ext-nfs-store
              subPath: cdddru-jobs

          securityContext:
            runAsUser: 0
            runAsGroup: 0

          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375

            - name: DOCKER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dockerhub-token
                  key: token
            - name: DOCKER_USER
              valueFrom:
                secretKeyRef:
                  name: dockerhub-token
                  key: username
            - name: DOCKER_SERVER
              valueFrom:
                secretKeyRef:
                  name: dockerhub-token
                  key: server
            - name: GIT_CRED
              valueFrom:
                secretKeyRef:
                  name: gitcred
                  key: id_rsa
            - name: KUBE_CRED
              valueFrom:
                secretKeyRef:
                  name: kubeconfig
                  key: config

      nodeSelector:
        kubernetes.io/hostname: n150-netbook

      volumes:
        - name: dockerconfig
          secret:
            secretName: dockerhub-cred

        - name: kubeconfig
          secret:
            secretName: kubeconfig

        - name: gitcred
          secret:
            secretName: gitcred

        - name: dind-storage
          hostPath:
            path: /tmp/dind/storage
            type: DirectoryOrCreate

        - name: site-data
          hostPath:
            path: /mnt/k3snfs/sites
            type: DirectoryOrCreate

        - name: nfs-store-02
          persistentVolumeClaim:
            claimName: cdddru-nfs-02
