apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-ddru
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: ${NFS_SERVER}
    path: /var/nfs/general
