Common:
  is_active: "true"
  job_name: "Main_ddru_sync_assets_yaml"
  job_type: tags-prefixed
  check_interval: 10
  variable_1: var_value_1
  variable_2: var_value_2
  variable_3: var_value_3
  variable_4: var_value_4
  variable_5: var_value_5

Git:
  do_git_clone: true
  git_repo_url: git@github.com:Direct-Dev-Ru/http2-nodejs-ddru.git
  git_private_key: /{{$HOME}}/.ssh/id_rsa
  git_branch: assets-branch
  git_tag_prefix: assets-
  git_start_tag: assets-0.0.0
  git_max_tag: assets-99.99.99
  git_start_tag_file: /tmp/cdddru/main-ddru-assets.tag
  git_local_folder: /tmp/cdddru/main-ddru-assets
  git_commit: ""

Deploy:
  do_manifest_deploy: false
  context_k8s:
  namespace_k8s:
  deployment_name_k8s:
  manifests_k8s:

Docker:
  do_docker_build: false
  docker_file:
  docker_image:
  docker_server:
  DOCKER_PASSWORD:
  docker_user:

Sync:
  do_subfolder_sync: true
  git_sub_folder: "/assets/"
  target_folder: "/app/nfs/main-site-data"
