Common:
  is_active: true
  job_name: "main ddru dev (yaml)"
  job_type: tags-prefixed
  check_interval: 20

Git:
  do_git_clone: true
  git_repo_url: git@github.com:Direct-Dev-Ru/http2-nodejs-ddru.git
  git_private_key: "{{$HOME}}/.ssh/id_rsa_1"
  git_branch: main
  git_tag_prefix: v
  git_start_tag: v0.0.0
  git_max_tag: v99.99.99
  git_target_tag: 
  git_start_tag_file: /tmp/cdddru/tag-main-ddru
  local_git_folder: /tmp/dev-repo-main-ddru
  git_commit: ""

Docker:
  do_docker_build: true
  docker_file: Dockerfile
  docker_image: kuznetcovay/ddru
  docker_server: https://index.docker.io/v1/
  docker_token: "{{$DOCKER_TOKEN}}"
  docker_user: kuznetcovay

Deploy:
  do_manifest_deploy: false
  context_k8s: default
  namespace_k8s: test-app
  deployment_name_k8s: main-site
  manifests_k8s: ./manifests/k8s-main-site-manifests.yaml

Sync:
  do_subfolder_sync: false
  git_sub_folder: "/assets/"
  target_folder: "/tmp/node/app/"

